const serviceData = [
  { image: '/uploads/images/tedarikcilerimiz/apetech.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/atlas_logo-02.png', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/autotech.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/bando-kayis.png', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/BERU.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/BLUE PRINT.jpg', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/CAVO.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/cifam.png', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/contitech-40.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/CORTECO.png', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/DAYCO.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/delphi.png', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/DENSO.jpg', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/DEPO.jpg', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/ELRİNG.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/FAG.jpg', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/febi.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/FERODO.png', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/FİL.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/FILTRON.png', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/gates-kayis.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/GOETZE ISS.png', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/graf.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/HELLA.png', delay: '300ms' },
  { image: '/uploads/images/tedarikcilerimiz/HELLUX.png', delay: '0ms' },
  { image: '/uploads/images/tedarikcilerimiz/HUTCHINSON.jpg', delay: '100ms' },
  { image: '/uploads/images/tedarikcilerimiz/İBRAŞ.png', delay: '200ms' },
  { image: '/uploads/images/tedarikcilerimiz/ideal-logo.png', delay: '300ms' },
]

export default serviceData
