const placeholderText =
  'Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı. Yorum yazısı.'

export const testimonialsData = [
  {
    id: 1,
    text: 'Gerçekten harika bir hizmet. Yakıt kalitesi ve personel ilgisi mükemmel. Her zaman tercihim Öcallar Petrol olacak.',
    author: 'Ahmet Yılmaz',
    designation: 'Şirket Sahibi',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 2,
    text: 'Yolda kalmıştım, hızlıca yardımcı oldular. Sadece bir petrol istasyonu değil, aynı zamanda bir yol arkadaşı gibiler. Teşekkürler!',
    author: 'Ayşe Kaya',
    designation: 'Öğretmen',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 3,
    text: 'Temiz tuvaletleri ve güler yüzlü çalışanları için bile tercih edilir. Market kısmı da oldukça zengin. Başarılar dilerim.',
    author: 'Mehmet Öztürk',
    designation: 'Esnaf',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 4,
    text: placeholderText,
    author: 'Müşteri Adı 4',
    designation: 'Ünvanı 4',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 5,
    text: placeholderText,
    author: 'Müşteri Adı 5',
    designation: 'Ünvanı 5',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 6,
    text: placeholderText,
    author: 'Müşteri Adı 6',
    designation: 'Ünvanı 6',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 7,
    text: placeholderText,
    author: 'Müşteri Adı 7',
    designation: 'Ünvanı 7',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 8,
    text: placeholderText,
    author: 'Müşteri Adı 8',
    designation: 'Ünvanı 8',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 9,
    text: placeholderText,
    author: 'Müşteri Adı 9',
    designation: 'Ünvanı 9',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 10,
    text: placeholderText,
    author: 'Müşteri Adı 10',
    designation: 'Ünvanı 10',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 11,
    text: placeholderText,
    author: 'Müşteri Adı 11',
    designation: 'Ünvanı 11',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 12,
    text: placeholderText,
    author: 'Müşteri Adı 12',
    designation: 'Ünvanı 12',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 13,
    text: placeholderText,
    author: 'Müşteri Adı 13',
    designation: 'Ünvanı 13',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 14,
    text: placeholderText,
    author: 'Müşteri Adı 14',
    designation: 'Ünvanı 14',
    image: '/uploads/images/resource/musteri.jpg',
  },
  {
    id: 15,
    text: placeholderText,
    author: 'Müşteri Adı 15',
    designation: 'Ünvanı 15',
    image: '/uploads/images/resource/musteri.jpg',
  },
]
